### ISSUE TITLE
iNav support

### ISSUE THREAD

**Issue by malarcky** [betaflight/betaflight-crsf-tx-scripts#7]
It would be possible to port this to use with iNav?

**Comment by codecae** [comment]
iNav can support it, but it can't be simply merged, as the CRSF and RX telemetry code is pretty far behind in iNav.

**Comment by mikeller** [comment]
iNav have their own set of TX lua scripts, have a look at https://github.com/iNavFlight, there is at least two of them. They do not yet seem to support configuring the firmware over lua though - but potentially there's work under way to add this.
